# We are using the ionicons icon set https://ionic.io/ionicons
# For example, to add a linkedin icon:
# <ion-icon name="logo-linkedin"></ion-icon>
# - icon: "logo-linkedin"

HEADER:
  label: "Show Contacts"

USER:
  role: "Web Developer"
  name: "Anand Karthik Kolla"
  username: "anandkarthik255" # <-- This needs to be the same as your GitHub username
  avatar: "config/assets/avatars/my-avatar.png"

INFO:
  - label: "Email"
    value: "anand.karthik.work.mail@gmail.com"
    icon: "mail-outline"
  - label: "Birthday"
    value: "NOV 11, 2002"
    icon: "calendar-outline"
  - label: "Location"
    value: "Hyderabad"
    icon: "location-outline"

SOCIAL:
  - icon: "logo-facebook"
    url: "https://facebook.com/"
  - icon: "logo-twitter"
    url: "https://twitter.com/"
  - icon: "logo-instagram"
    url: "https://instagram.com/"
  - icon: "logo-linkedin"
    url: "https://www.linkedin.com/anandkarthik255"
  - icon: "logo-github"
    url: "https://github.com/anandkarthik255"
  - icon: "logo-dribbble"
    url: "https://dribbble.com/"
