HEADER:
  label: "Resume"

EDUCATION:
  enabled: true
  label: "Education"
  items:
    - period: "2019 — 2023"
      institution: "CVR College of Engineering"
      description: "Bachelor of Technology in Computer Science and Engineering. Relevant coursework includes OOPs through Java, Data Structures and Algorithms, Operating Systems, Computer Networks, Database Management Systems, Web Technologies, and Software Engineering with Agile methodology."

EXPERIENCE:
  enabled: true
  label: "Experience"
  items:
    - period: "2022 — Present"
      position: "Developer Consultant @ Oracle"
      description: "Developed real-time applications using React and Node.js for backend infrastructure management. Customized Python scripts for workflow automation, optimized MySQL databases, and integrated RESTful APIs for system interactions."
    - period: "2022 — 2023"
      position: "Developer Consultant Intern @ Oracle"
      description: "Contributed to the development of real-time applications with React and Node.js. Enhanced workflow processes with Python, designed MySQL databases, and supported compliance with safety protocols through monitoring systems."

LANGUAGES:
  enabled: true
  display_progress_bars: true
  display_percentage_values: true
  label: "Languages"
  items:
    - language: "English"
      proficiency: "90%"
    - language: "Telugu"
      proficiency: "80%"
    - language: "Hindi"
      proficiency: "70%"

SKILLS:
  enabled: true
  display_progress_bars: true
  display_percentage_values: true
  label: "My Skills"
  items:
    - skill: "JavaScript"
      proficiency: "80%"
    - skill: "Java"
      proficiency: "70%"
    - skill: "Python"
      proficiency: "70%"
    - skill: "MySQL"
      proficiency: "70%"
    - skill: "React"
      proficiency: "80%"
    - skill: "MERN Stack"
      proficiency: "75%"
    - skill: "RESTful APIs"
      proficiency: "75%"
